#!/bin/bash
set -e

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOSQL
    CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\`;

    CREATE USER IF NOT EXISTS '${APP_DB_USER}'@'%' IDENTIFIED BY '${APP_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}\`.* TO '${APP_DB_USER}'@'%';

    FLUSH PRIVILEGES;
EOSQL