spring.application.name=DCAVA Backend
server.forward-headers-strategy=framework

# Puerto
server.port=${PORT:8080}

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=30000

# Frontend
app.frontend-urls=${FRONTEND_URLS:http://localhost:3000}

# Entorno
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Uploads
spring.servlet.multipart.max-file-size=8MB
spring.web.resources.static-locations=file:uploads/

# Firebase
# Credenciales (vienen desde el .env)
app.firebase.project-id=${FIREBASE_PROJECT_ID:}
app.firebase.private-key-id=${FIREBASE_PRIVATE_KEY_ID:}
app.firebase.private-key=${FIREBASE_PRIVATE_KEY:}
app.firebase.client-email=${FIREBASE_CLIENT_EMAIL:}
app.firebase.client-id=${FIREBASE_CLIENT_ID:}

# Constantes públicas de Google (con valores por defecto si no están en .env)
app.firebase.type=${FIREBASE_TYPE:service_account}
app.firebase.auth-uri=${FIREBASE_AUTH_URI:https://accounts.google.com/o/oauth2/auth}
app.firebase.token-uri=${FIREBASE_TOKEN_URI:https://oauth2.googleapis.com/token}
app.firebase.auth-provider-cert-url=${FIREBASE_AUTH_PROVIDER_X509_CERT_URL:https://www.googleapis.com/oauth2/v1/certs}
app.firebase.universe-domain=${FIREBASE_UNIVERSE_DOMAIN:googleapis.com}

# Cloudflare R2
app.r2.endpoint=${R2_ENDPOINT}
app.r2.access-key=${R2_ACCESS_KEY}
app.r2.secret-key=${R2_SECRET_KEY}
app.r2.bucket=${R2_BUCKET}
app.r2.public-url=${R2_PUBLIC_URL}
