spring.application.name=DCAVA Backend

#localhost 8080 default
server.port=${APP_PORT:8080}

#Database
spring.datasource.url=${DATABASE_URL:jdbc:mysql://127.0.0.1/dcava_db_test}
spring.datasource.username=${DATABASE_USER:dcava_app}
spring.datasource.password=${DATABASE_PASSWORD:yv^z7fPK56m@^nBstigMbZ4ES}

#Frontend
app.frontend-urls=${FRONTEND_URLS:http://localhost:3000}

#Entorno
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=5MB

app.upload.dir=uploads
spring.web.resources.static-locations=file:uploads/

# Cloudflare R2
app.r2.endpoint=${R2_ENDPOINT}
app.r2.access-key=${R2_ACCESS_KEY}
app.r2.secret-key=${R2_SECRET_KEY}
app.r2.bucket=${R2_BUCKET}
app.r2.public-url=${R2_PUBLIC_URL}
