spring.application.name=DCAVA Backend

server.port=${APP_PORT:8080}

#Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

#Frontend
app.frontend-urls=${FRONTEND_URLS:http://localhost:3000}

#Entorno
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=8MB

spring.web.resources.static-locations=file:uploads/

app.firebase.credentials-json=${FIREBASE_CREDENTIALS_JSON:}


# Cloudflare R2
app.r2.endpoint=${R2_ENDPOINT}
app.r2.access-key=${R2_ACCESS_KEY}
app.r2.secret-key=${R2_SECRET_KEY}
app.r2.bucket=${R2_BUCKET}
app.r2.public-url=${R2_PUBLIC_URL}
